### ISSUE TITLE
Colors don't show when using a hash(object) in Stylus

### ISSUE THREAD

**Issue by gandhiShepard** [abe33/atom-color-highlight#75]
I just found all this color highlight and minimap stuff today and it all f*cking rocks! Awesome work! 

I have a fringe case issue with using colors with hashes(object) in Stylus. This works great when using variables, however, it doesn't when calling a color inside a hash. Is this something that can be addressed, or is this a technical impossibility? This screen shot shows the issue. 

Using `color.orange` reveals no color highlighting.

![screen shot 2015-02-06 at 6 48 17 am](https://cloud.githubusercontent.com/assets/8546059/6079556/5a3f287e-adcc-11e4-982e-6adbf7dcc860.png)

**Comment by abe33** [comment]
Thanks for bringing this up. 
I'm using stylus myself and I also use colors hashes frequently, so I have thought about this for some time now and I'm planning to support it one day, even if I can't give any ETA yet. 
The thing is that it imply rewriting a big part of the variables parsing stuff so that it can work in a more context-aware fashion, but I haven't started looking seriously at how to do it yet.

Any help is welcome if someone feel to take a shot at this feature. The color parsing code is available as a npm module here: abe33/pigments

**Comment by gandhiShepard** [comment]
Coool. Thanks for the response! Does it make sense to just roll something out for Stylus users only? I feel like the Stylus community needs to make some more noise.

**Comment by abe33** [comment]
Variables from a hash will now be highlighted properly if they are defined in the same file. Sadly I can't support that feat in the project palette yet as `atom.workspace.scan` doesn't handle multiline regexp searches. So I would only get `color = {` and re-parsing files aren't really an option for the moment.

**Comment by gandhiShepard** [comment]
Cool! Gotcha.
