### ISSUE TITLE
Color highlights all grayscale

### ISSUE THREAD

**Issue by plttn** [abe33/atom-color-highlight#80]
Not sure whether it's a bug with color highlight or palette finder, but on Windows, all my highlights are gray in the buffer (but not the minimap). 
![2015-02-20_10-48-14](https://cloud.githubusercontent.com/assets/7369280/6307095/0c49cd18-b8ee-11e4-8f2d-6bd49a19497f.png)

Even more oddly, using a atom-sync'd instance on my MBP, with the only difference being that I'm using Unity UI, it displays fine.

**Comment by abe33** [comment]
Wow, this one is a first!

My first guess is that there's an issue with the DOM elements. Markers use a little trick to have the transparent background checker and I think it fails in that case. 

Let me explain first how it works, I'll need you to inspect the markers after that. 
The `.regions` divs in the markers should have a `background-color` property defined in their `styles` attribute, then they also have `::before` and `::after` pseudo-elements, the `::before` displays the checker, and the `::after` element inherits the background-color from the `.region` div using `background-color: inherit`. Both have a `z-index` of `-1` so that they appears below the text contained inside the region.

As I can see on you screen shot the markers have their checker div, the text color seems fine too which mean the color parsing was properly done and the color was valid (otherwise no marker is displayed and the text color couldn't have been computed). So I think there's either an issue with the `background-color` on either the `.region` or the `::after` element, or an issue with the ordering of `::before` and `::after` pseudo-elements. Can you inspect the marker and confirm that there isn't some other styles that pollutes the markers' regions?

If you are not sure what to check you can also take some screenshots for me of the inspector with the various elements selected like in the example below: 

![capture](http://i.imgur.com/IGljkcE.png)

I would need that for the `.region` element and its `::before` and `::after` pseudo-elements.

**Comment by plttn** [comment]
Turns out my packages weren't synced 100%. Conflict between selection-outlines and this package. 

Anyways here's the .region, ::before, ::after


![2015-02-21_10-14-52](https://cloud.githubusercontent.com/assets/7369280/6315296/8c2ae840-b9b2-11e4-976e-52d4f38b1fde.png)

![2015-02-21_10-15-54](https://cloud.githubusercontent.com/assets/7369280/6315297/9d217a06-b9b2-11e4-84cf-a22642c4f9c4.png)

![2015-02-21_10-16-59](https://cloud.githubusercontent.com/assets/7369280/6315302/c8564a12-b9b2-11e4-842c-73472d2fb504.png)
