### ISSUE TITLE
Incorrect highlight position after Chinese characters

### ISSUE THREAD

**Issue by yangg** [abe33/atom-color-highlight#93]
This is a javascript file.
```javascript
  var rooms = [
    { id: 1, name: '这里是中文', color: '#257e4a'}
  ];
```
![](http://ww1.sinaimg.cn/large/6eba2496gw1esilfwxgcij20dv011mx6.jpg)

**Comment by abe33** [comment]
Have you tried [pigments](https://atom.io/packages/pigments) instead of `atom-color-highlight`?
Actually pigments is the successor of `atom-color-highlight` and also a complete rewrite in order to solve many performances issues. 
And I've just tried your sample in `pigments` and the problem is not present.

**Comment by yangg** [comment]
OK, pigments solved my problem, tks.
